### ISSUE TITLE
chef_deep_merge incorrectly merging override arrays

### ISSUE THREAD

**Issue by sdelano** [chef-boneyard/chef_objects#84]
In `chef_deep_merge:merge`, when merging a default attribute that is an array with an override attribute that is an array that looks like the following:

``` json
{
  "default": { "foo": ["bar"] },
  "override": { "foo": ["baz"] }
}
```

The result is a merged array, where `node["foo"]` is equivalent to:

``` json
["bar", "baz"]
```

What the client actually sees when evaluating `node["foo"]` is:

```
["baz"]
```

and the recipe treats the value as such. This `deep_merge` bug, which only occurs when merging attributes before sending the JSON representation to SOLR for indexing, breaks search when trying to differentiate on the `"foo"` attribute. The following searches will both work for a node with the above override, and only the search on the `"baz"` key should:
- `knife search node foo:bar` (should not return node)
- `knife search node foo:baz` (should return node)

**Comment by kwilczynski** [comment]
@sdelano :+1:

**Comment by sdelano** [comment]
For more context, the code that exercises the `chef_deep_merge` is in `chef_node:ejson_for_indexing`.

**Comment by tylercloke** [comment]
Specifically, we should not be merging arrays, but overriding them in the erlang deep merge code.

**Comment by sdelano** [comment]
@tylercloke correct. Please double-check with @danielsdeleo on the client-side implementation of this.

**Comment by danielsdeleo** [comment]
Chef's tests for this behavior are here: https://github.com/opscode/chef/blob/01c7e4dc402c3252a96ba05680747fe773b78f39/spec/unit/node/attribute_spec.rb#L331-L353

**Comment by kwilczynski** [comment]
@sdelano @tylercloke do you think we can fix this issue easily, or is it something we need to hold on with for later?

**Comment by seth** [comment]
So here are the calls to chef_deep_merge: https://github.com/opscode/oc_erchef/blob/master/apps/chef_objects/src/chef_node.erl#L148-L150

Looks at the tests that @danielsdeleo linked, I think we always want the behavior for arrays to take the value from the merge object and not do any concatenation of array values. If that's the case, the fix will be quite small.

**Comment by sdelano** [comment]
This was fixed by: https://github.com/chef/oc_erchef/commit/4117fed6cb5f4f7f1eab0d7f9ff0a2e808155e90
